# Site settings
title: Dan Carroll on GitHub
author: Dan Carroll
email: dcarroll809@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my GitHub gateway. This is the personal frontpage of Dan Carroll 
  for his GitHub activities and to showcase his work and interests. This site 
  is created and maintained with [Jekyll](https://jekyllrb.com/).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dan-carroll.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-9F0N5QZNRB
linkedin_username: dan-carroll-in-florida
twitter_username: FloriDanOnline
github_username:  dan-carroll
instagram_username: dcarroll809

# My Add-Ins
blog1_title: Dan Reads
blog1_url: https://dan-carroll.github.io/danreads/
blog2_title: 365 Day Graphic Design Challenge
blog2_url: https://dan-carroll.github.io/graphic-design-challenge/
blog3_title: My Python Pages
blog3_url: https://dancarroll.pythonanywhere.com/
blog4_title: Rather Be Coding
blog4_url: #


# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

show_excerpts: true
